name: Your New Jekyll Site
permalink: /:categories/:title
sass:
  syntax: scss
  style: expanded
  sass_dir: _sass
gems:
 - jekyll-coffeescript
exclude:
 - README.md
 - Gemfile
 - Gemfile.lock
 - vendor
