name: Your New Jekyll Site
highlighter: pygments
permalink: /:categories/:title
sass:
  syntax: scss
  style: expanded
exclude:
 - unicorn.rb
 - README.md
 - Procfile
 - Gemfile
 - Gemfile.lock
 - config.ru
 - vendor
